### PR TITLE
PAF-129/ PAF-128 - Fix bug to add country from list and validate country textbox.

### PR DESCRIPTION
**Pull request by TemitopeAyokuHO**
## What?
[PAF-128](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-128) Country' fields allow any text 
[PAF-129](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-129)- All 'Country' fields allow any text without the use of drop down list
## Why?
remove any url from the input text and accept validation entry.
this validation with control the textbox for both country and phone numbers
## How?

- added validation attribute in the field/index.js file 
- added validation message in the validation.js file

## Testing?
Manual testing via UI

### CODE REVIEW

**Review by jamiecarterHO — COMMENTED** [review]
Screenshot 2023-12-15 at 13 47 58
If we're removing the ability to type in an entry to these fields we should also remove or update any bits of hint text that suggest 'Start to type...' or similar.

Otherwise the update to code looks fine - stops users from entering a non-country-list entry here. 

I would actually question if this is a bug in the first place. I wonder from a UCD perspective whether any text entry should be allowed in case the `countryList` becomes out of date or is incomplete. It may be more of an advisory list. As far as I know every other HOF form field with a country select has the typeahead and accepts non-list entry. 

If business stakeholders have said these fields must absolutely have a value from the `countryList` then no problem. But might be worth confirming with the ticket reporter.

**Comment by TemitopeAyokuHO** [comment]
The business came back with responses 
"I have had a think about the autocomplete component. I think the best solution to the problem you highlighted would be :
to include validation on the field when it is not empty, for example letting the user know that they have entered an option that is not available
the data should also clear if the user empties the field, so their previous response would not appear on the CYA page"

I have added a validation on each textbox for both country and phone number. a new ticket was created for this PAF-128 but i have made the modification on this branch

**Comment by jamiecarterHO** [comment]
Now that the phone number fields are required on the page "Do you want to tell us about another location where the crime is taking place?" if I choose 'no' I still need to go back and fill in a phone number on the 'yes' bit before I can continue. I think the phone number field might need a `dependent: {field: 'crime-location',value: 'yes'}` in `/fields/index.js` like the other fields in the address do.

**Comment by jamiecarterHO** [comment]
> The business came back with responses "I have had a think about the autocomplete component. I think the best solution to the problem you highlighted would be : to include validation on the field when it is not empty, for example letting the user know that they have entered an option that is not available the data should also clear if the user empties the field, so their previous response would not appear on the CYA page"

The business comment above seems to me to suggest that empty field should be an option, but if they want to put something it should be a country from the list. Now that fields are required they must have a value, and once a value from the list has been added it can't be removed again except with another one from the list.

**Comment by TemitopeAyokuHO** [comment]
> Now that the phone number fields are required on the page "Do you want to tell us about another location where the crime is taking place?" if I choose 'no' I still need to go back and fill in a phone number on the 'yes' bit before I can continue. I think the phone number field might need a `dependent: {field: 'crime-location',value: 'yes'}` (or whatever choice is conditional for other phone fields) in `/fields/index.js` like the other fields in the address do.

I have just realised this issue after replicating it, i will be fixing it

**Comment by TemitopeAyokuHO** [comment]
> > The business came back with responses "I have had a think about the autocomplete component. I think the best solution to the problem you highlighted would be : to include validation on the field when it is not empty, for example letting the user know that they have entered an option that is not available the data should also clear if the user empties the field, so their previous response would not appear on the CYA page"
> 
> The business comment above seems to me to suggest that empty field should be an option, but if they want to put something it should be a country from the list. Now that fields are required they must have a value, and once a value from the list has been added it can't be removed again except with another one from the list.

Reason for doing this was if the user enters a country which is not from the list, in the summary page the country will not render. to fix this bug a validation control is necessary or dropdown menu. I hope this answers that?

**Comment by jamiecarterHO** [comment]
> Reason for doing this was if the user enters a country which is not from the list, in the summary page the country will not render. to fix this bug a validation control is necessary or dropdown menu. I hope this answers that?

Yes, that makes sense to me, thanks.

**Review by jamiecarterHO — APPROVED** [review]

**Pull request merged**
